[package]
name = "miners"
version = "0.1.0"
authors = ["carsin <carsin@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bracket-terminal = "0.8.1"
bracket-lib = { version = "0.8.1", features = [ "specs" ] }
specs = { version = "0.16.1", features = ["specs-derive"] }
rand = "*"
