[package]
name = "miners"
version = "0.1.0"
authors = ["carsin <carsin@users.noreply.github.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
specs = { version = "0.16.1", features = ["specs-derive"] }
